apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-config
  namespace: gitops
spec:
  serviceAccountName: gitops-sa
  interval: 30s
  path: ./env/dev01
  prune: true
  sourceRef:
    kind: GitRepository
    name: clusters
