#! Install MetalLB using an Helm chart.

#! Create a Secret metallb-values in namespace metallb-system to define the MetalLB configuration.
#! For example:
#!   apiVersion: v1
#!   kind: Secret
#!   metadata:
#!     name: metallb-values
#!     namespace: metallb-system
#!   type: Opaque
#!   stringData:
#!     values.yaml: |
#!       configInline:
#!         address-pools:
#!         - name: default
#!           protocol: layer2
#!           addresses:
#!           - 10.220.6.133-10.220.6.133

apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  targetNamespace: metallb-system
  interval: 30s
  chart:
    spec:
      chart: metallb
      version: v0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb
  valuesFrom:
  - kind: Secret
    name: metallb-values
    optional: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  url: https://metallb.github.io/metallb
