apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  targetNamespace: podinfo
  interval: 30s
  chart:
    spec:
      chart: podinfo
      version: 6.1.8
      sourceRef:
        kind: HelmRepository
        name: podinfo
  valuesFrom:
  - kind: Secret
    name: podinfo-base-values
  - kind: Secret
    name: podinfo-values
    optional: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
  namespace: podinfo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: podinfo-podinfo
  ingress:
  - ports:
    - port: 9898
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1m
  url: https://stefanprodan.github.io/podinfo
