apiVersion: v1
kind: Secret
metadata:
  name: podinfo-base-values
  namespace: podinfo
type: Opaque
stringData:
  values.yaml: |
    replicaCount: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-values
  namespace: podinfo
type: Opaque
stringData:
  values.yaml:
