apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: spring-on-k8s
spec:
 rules:
  - host: springonk8s.10.220.6.133.nip.io
    http:
      paths:
      - backend:
          service:
            name: app
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
